spring.application.name=multidb-app

# MySQL DataSource Configuration
db1.datasource.jdbc-url=jdbc:mysql://localhost:3306/healthcare_db
db1.datasource.username=root
db1.datasource.password=root

db2.datasource.jdbc-url=jdbc:postgresql://localhost:5432/teluskodb
db2.datasource.username=postgres
db2.datasource.password=root
